version: '3'
services: 
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            PGDATA: /var/postgres_data
        volumes: 
            - ./tmp/db:/var/postgres_data
        ports:
        - "5432:5432"
    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - .:/todo-server
        ports: 
            - 3000:3000
        depends_on: 
            - db
