version: '3'
services: 
    db:
        image: postgres
        volumes: 
            - ./tmp/db:/var/lib/postgres/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "${DATABASE_PORT}:5432"
    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - .:/todo-server
        ports: 
            - ${RAILS_PORT}:3000
        depends_on: 
            - db
